# DataSource configuration for the MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Enable logging for JDBC SQL statements (for dev/testing only)
# DO NOT use in production as it may log sensitive data like usernames
logging.level.org.springframework.jdbc.core=TRACE 


