# configu exposure actuator endponit
management.endpoint.web.exposure.include=health,info


#start env information
management.info.env.enabled=true

# start Actuator sercurity
management.security.enabled=true

info.app.name=my super cool app
info.app.description=A crazy fun app.woow!!!
info.app.version=1.0.0
